version: 2

sources:
  - name: northwind
    description: This is a replica of the Postgres database used by our app
    tables:
    - name: categories 
      description: This table contains information about the categories
  
    - name: customers 
      description: This table contains information about the customers

    - name: employee_territories 
      description: This table contains information about the employees territories 
      
    - name: employees 
      description: This table contains information about the employees

    - name: order_details 
      description: This table contains information about the order details, with the products in an order

    - name: orders 
      description: This table contains information about the orders 

    - name: products 
      description: This table contains information about the products

    - name: region 
      description: This table contains information about the regions

    - name: shippers 
      description: This table contains information about the shippers

    - name: suppliers 
      description: This table contains information about the suppliers

    - name: territories 
      description: This table contains information about the territories

    - name: us_states 
      description: This table contains information about the us statesss
